### PR TITLE
Check if cached or browser lang is available for use, before setting it on init

### PR DESCRIPTION
**Pull request by zhukov-vlad**

### CODE REVIEW

**Comment by DmitryEfimenko** [comment]
This PR really needs to go in. It's got an important fix the absense of which is really messing up my app:
```ts
this.translateService.getLangs().includes(currentLang)
```
Can this please be rebased and merged in?

**Comment by DmitryEfimenko** [comment]
At the very minimum, please let us know if this PR is abandoned or not so that we know whether to look for an alternative fix

**Comment by jgpacheco** [comment]
@DmitryEfimenko Any help is welcome. If you feel comfortable, please go ahead and rebase it. We can validate, merge and publish as soon as the pull request conflicts are resolved.

**Comment by DmitryEfimenko** [comment]
I don't have permissions to push changes to this PR, so I created a separate one: https://github.com/jgpacheco/ngx-translate-cache/pull/9

**Comment by jgpacheco** [comment]
Thank you @zhukov-vlad and @DmitryEfimenko for the fix and apologies for the delayed response.

**Pull request closed without merging**
